version: '3'
services:
  myapp:
    container_name: myprj-be
    image: $ECR_URL/$ECR_IMAGE
    ports:
      - 3000:3000
    environment:
      S3_BUCKET: ${S3_BUCKET}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ECR_URL: ${ECR_URL}
      ECR_IMAGE: ${DB_HOST}
    logging:
      driver: awslogs
      options:
        awslogs-region: ${REGION}
        awslogs-group: myprjLogGroup
        awslogs-create-group: "true"