variable "default_region" {}
variable "environment" {}
variable "instance_type" {}
variable "artifact_bucket" {}
variable "vpc_id" {}
variable "ecr_repo_name" {}
variable "ecr_repository_url" {}
variable "alb_dns" {}
variable "alb_arn" {}
variable "ec2_sg_id" {}
variable "ec2_subnet1_id" {}
variable "ec2_subnet2_id" {}