default_region  = "ap-southeast-1"
environment     = "dev"
instance_type   = "t2.micro"
artifact_bucket = "terraform-test-bucket-020197"
db_name         = "myprj"
db_user         = "myprj"
ecr_repo_name   = "myprj"